### ISSUE TITLE
I am getting the following error, when trying to run the test within docker container (as per README).

### ISSUE THREAD

**Issue by jaffamonkey** [Tedc0819/cucumber-web#1]
I am getting the following error, when trying to run the test within docker container (as per README).

Example: 
1) Scenario: Reading documentation - features/documentation.feature:6
   Step: Before
   Step Definition: features/step_definitions/hooks.js:7
   Message:
     TypeError: Cannot read property 'browser' of undefined
         at App.initDriver (/app/app.js:79:15)
         at World.<anonymous> (/app/features/step_definitions/hooks.js:9:16)

**Comment by jaffamonkey** [comment]
it's actually ok, I just used "export NODE_ENV=local export TEST_CLIENT=chrome grunt test"
